// 전 세계 국가 데이터 (Select2)
	const countryList = [
		        { id: '', text: '여행할 국가를 검색하세요' },
		        // --- 아시아 ---
		        { id: 'KR', text: '🇰🇷 대한민국 (South Korea)' },
		        { id: 'JP', text: '🇯🇵 일본 (Japan)' },
		        { id: 'VN', text: '🇻🇳 베트남 (Vietnam)' },
		        { id: 'TH', text: '🇹🇭 태국 (Thailand)' },
		        { id: 'TW', text: '🇹🇼 대만 (Taiwan)' },
		        { id: 'CN', text: '🇨🇳 중국 (China)' },
		        { id: 'PH', text: '🇵🇭 필리핀 (Philippines)' },
		        { id: 'HK', text: '🇭🇰 홍콩 (Hong Kong)' },
		        { id: 'MO', text: '🇲🇴 마카오 (Macau)' },
		        { id: 'SG', text: '🇸🇬 싱가포르 (Singapore)' },
		        { id: 'MY', text: '🇲🇾 말레이시아 (Malaysia)' },
		        { id: 'ID', text: '🇮🇩 인도네시아 (Indonesia)' },
		        { id: 'MN', text: '🇲🇳 몽골 (Mongolia)' },
		        { id: 'IN', text: '🇮🇳 인도 (India)' },
		        { id: 'NP', text: '🇳🇵 네팔 (Nepal)' },
		        { id: 'LA', text: '🇱🇦 라오스 (Laos)' },
		        { id: 'KH', text: '🇰🇭 캄보디아 (Cambodia)' },
		        { id: 'MV', text: '🇲🇻 몰디브 (Maldives)' },
		        
		        // --- 유럽 ---
		        { id: 'GB', text: '🇬🇧 영국 (United Kingdom)' },
		        { id: 'FR', text: '🇫🇷 프랑스 (France)' },
		        { id: 'IT', text: '🇮🇹 이탈리아 (Italy)' },
		        { id: 'ES', text: '🇪🇸 스페인 (Spain)' },
		        { id: 'CH', text: '🇨🇭 스위스 (Switzerland)' },
		        { id: 'DE', text: '🇩🇪 독일 (Germany)' },
		        { id: 'IE', text: '🇮🇪 아일랜드 (Ireland)' }, // 여기 있습니다!
		        { id: 'AT', text: '🇦🇹 오스트리아 (Austria)' },
		        { id: 'CZ', text: '🇨🇿 체코 (Czechia)' },
		        { id: 'HU', text: '🇭🇺 헝가리 (Hungary)' },
		        { id: 'PT', text: '🇵🇹 포르투갈 (Portugal)' },
		        { id: 'HR', text: '🇭🇷 크로아티아 (Croatia)' },
		        { id: 'GR', text: '🇬🇷 그리스 (Greece)' },
		        { id: 'NL', text: '🇳🇱 네덜란드 (Netherlands)' },
		        { id: 'BE', text: '🇧🇪 벨기에 (Belgium)' },
		        { id: 'SE', text: '🇸🇪 스웨덴 (Sweden)' },
		        { id: 'DK', text: '🇩🇰 덴마크 (Denmark)' },
		        { id: 'NO', text: '🇳🇴 노르웨이 (Norway)' },
		        { id: 'FI', text: '🇫🇮 핀란드 (Finland)' },
		        { id: 'PL', text: '🇵🇱 폴란드 (Poland)' },
		        { id: 'IS', text: '🇮🇸 아이슬란드 (Iceland)' },
		        { id: 'TR', text: '🇹🇷 튀르키예 (Turkey)' },
		        { id: 'GE', text: '🇬🇪 조지아 (Georgia)' },

		        // --- 북미/남미 ---
		        { id: 'US', text: '🇺🇸 미국 (United States)' },
		        { id: 'CA', text: '🇨🇦 캐나다 (Canada)' },
		        { id: 'MX', text: '🇲🇽 멕시코 (Mexico)' },
		        { id: 'BR', text: '🇧🇷 브라질 (Brazil)' },
		        { id: 'AR', text: '🇦🇷 아르헨티나 (Argentina)' },
		        { id: 'CL', text: '🇨🇱 칠레 (Chile)' },
		        { id: 'PE', text: '🇵🇪 페루 (Peru)' },
		        { id: 'CO', text: '🇨🇴 콜롬비아 (Colombia)' },

		        // --- 오세아니아 ---
		        { id: 'AU', text: '🇦🇺 호주 (Australia)' },
		        { id: 'NZ', text: '🇳🇿 뉴질랜드 (New Zealand)' },
		        { id: 'GU', text: '🇬🇺 괌 (Guam)' },
		        { id: 'MP', text: '🇲🇵 사이판 (Northern Mariana Islands)' },

		        // --- 중동/아프리카 ---
		        { id: 'AE', text: '🇦🇪 아랍에미리트 (UAE/Dubai)' },
		        { id: 'SA', text: '🇸🇦 사우디아라비아 (Saudi Arabia)' },
		        { id: 'EG', text: '🇪🇬 이집트 (Egypt)' },
		        { id: 'MA', text: '🇲🇦 모로코 (Morocco)' },
		        { id: 'ZA', text: '🇿🇦 남아공 (South Africa)' },
		        { id: 'GH', text: '🇬🇭 가나 (Ghana)' },
		        { id: 'TZ', text: '🇹🇿 탄자니아 (Tanzania)' },
		        { id: 'KE', text: '🇰🇪 케냐 (Kenya)' },
		        { id: 'MU', text: '🇲🇺 모리셔스 (Mauritius)' },
		        { id: 'SC', text: '🇸🇨 세이셸 (Seychelles)' },
		        
		        // --- 기타 전세계 국가들 ---
		        { id: 'AF', text: '🇦🇫 아프가니스탄 (Afghanistan)' },
		        { id: 'AL', text: '🇦🇱 알바니아 (Albania)' },
		        { id: 'DZ', text: '🇩🇿 알제리 (Algeria)' },
		        { id: 'AD', text: '🇦🇩 안도라 (Andorra)' },
		        { id: 'AO', text: '🇦🇴 앙골라 (Angola)' },
		        { id: 'AM', text: '🇦🇲 아르메니아 (Armenia)' },
		        { id: 'AZ', text: '🇦🇿 아제르바이잔 (Azerbaijan)' },
		        { id: 'BH', text: '🇧🇭 바레인 (Bahrain)' },
		        { id: 'BD', text: '🇧🇩 방글라데시 (Bangladesh)' },
		        { id: 'BB', text: '🇧🇧 바베이도스 (Barbados)' },
		        { id: 'BY', text: '🇧🇾 벨라루스 (Belarus)' },
		        { id: 'BZ', text: '🇧🇿 벨리즈 (Belize)' },
		        { id: 'BT', text: '🇧🇹 부탄 (Bhutan)' },
		        { id: 'BO', text: '🇧🇴 볼리비아 (Bolivia)' },
		        { id: 'BA', text: '🇧🇦 보스니아 헤르체고비나' },
		        { id: 'BW', text: '🇧🇼 보츠와나 (Botswana)' },
		        { id: 'BN', text: '🇧🇳 브루나이 (Brunei)' },
		        { id: 'BG', text: '🇧🇬 불가리아 (Bulgaria)' },
		        { id: 'BF', text: '🇧🇫 부르키나파소 (Burkina Faso)' },
		        { id: 'BI', text: '🇧🇮 부룬디 (Burundi)' },
		        { id: 'CV', text: '🇨🇻 카보베르데 (Cabo Verde)' },
		        { id: 'CM', text: '🇨🇲 카메룬 (Cameroon)' },
		        { id: 'CR', text: '🇨🇷 코스타리카 (Costa Rica)' },
		        { id: 'CI', text: '🇨🇮 코트디부아르 (Ivory Coast)' },
		        { id: 'HR', text: '🇭🇷 크로아티아 (Croatia)' },
		        { id: 'CU', text: '🇨🇺 쿠바 (Cuba)' },
		        { id: 'CY', text: '🇨🇾 키프로스 (Cyprus)' },
		        { id: 'DO', text: '🇩🇴 도미니카 공화국' },
		        { id: 'EC', text: '🇪🇨 에콰도르 (Ecuador)' },
		        { id: 'EE', text: '🇪🇪 에스토니아 (Estonia)' },
		        { id: 'ET', text: '🇪🇹 에티오피아 (Ethiopia)' },
		        { id: 'FJ', text: '🇫🇯 피지 (Fiji)' },
		        { id: 'GA', text: '🇬🇦 가봉 (Gabon)' },
		        { id: 'GT', text: '🇬🇹 과테말라 (Guatemala)' },
		        { id: 'HN', text: '🇭🇳 온두라스 (Honduras)' },
		        { id: 'IR', text: '🇮🇷 이란 (Iran)' },
		        { id: 'IQ', text: '🇮🇶 이라크 (Iraq)' },
		        { id: 'IL', text: '🇮🇱 이스라엘 (Israel)' },
		        { id: 'JM', text: '🇯🇲 자메이카 (Jamaica)' },
		        { id: 'JO', text: '🇯🇴 요르단 (Jordan)' },
		        { id: 'KZ', text: '🇰🇿 카자흐스탄 (Kazakhstan)' },
		        { id: 'KW', text: '🇰🇼 쿠웨이트 (Kuwait)' },
		        { id: 'KG', text: '🇰🇬 키르기스스탄 (Kyrgyzstan)' },
		        { id: 'LV', text: '🇱🇻 라트비아 (Latvia)' },
		        { id: 'LB', text: '🇱🇧 레바논 (Lebanon)' },
		        { id: 'LY', text: '🇱🇾 리비아 (Libya)' },
		        { id: 'LT', text: '🇱🇹 리투아니아 (Lithuania)' },
		        { id: 'LU', text: '🇱🇺 룩셈부르크 (Luxembourg)' },
		        { id: 'MG', text: '🇲🇬 마다가스카르 (Madagascar)' },
		        { id: 'MT', text: '🇲🇹 몰타 (Malta)' },
		        { id: 'MC', text: '🇲🇨 모나코 (Monaco)' },
		        { id: 'ME', text: '🇲🇪 몬테네그로 (Montenegro)' },
		        { id: 'MM', text: '🇲🇲 미얀마 (Myanmar)' },
		        { id: 'NA', text: '🇳🇦 나미비아 (Namibia)' },
		        { id: 'NG', text: '🇳🇬 나이지리아 (Nigeria)' },
		        { id: 'OM', text: '🇴🇲 오만 (Oman)' },
		        { id: 'PK', text: '🇵🇰 파키스탄 (Pakistan)' },
		        { id: 'PA', text: '🇵🇦 파나마 (Panama)' },
		        { id: 'PY', text: '🇵🇾 파라과이 (Paraguay)' },
		        { id: 'QA', text: '🇶🇦 카타르 (Qatar)' },
		        { id: 'RO', text: '🇷🇴 루마니아 (Romania)' },
		        { id: 'RU', text: '🇷🇺 러시아 (Russia)' },
		        { id: 'RS', text: '🇷🇸 세르비아 (Serbia)' },
		        { id: 'SK', text: '🇸🇰 슬로바키아 (Slovakia)' },
		        { id: 'SI', text: '🇸🇮 슬로베니아 (Slovenia)' },
		        { id: 'LK', text: '🇱🇰 스리랑카 (Sri Lanka)' },
		        { id: 'SY', text: '🇸🇾 시리아 (Syria)' },
		        { id: 'TJ', text: '🇹🇯 타지키스탄 (Tajikistan)' },
		        { id: 'TN', text: '🇹🇳 튀니지 (Tunisia)' },
		        { id: 'UA', text: '🇺🇦 우크라이나 (Ukraine)' },
		        { id: 'UY', text: '🇺🇾 우루과이 (Uruguay)' },
		        { id: 'UZ', text: '🇺🇿 우즈베키스탄 (Uzbekistan)' },
		        { id: 'VE', text: '🇻🇪 베네수엘라 (Venezuela)' },
		        { id: 'YE', text: '🇾🇪 예멘 (Yemen)' },
		        { id: 'ZM', text: '🇿🇲 잠비아 (Zambia)' },
		        { id: 'ZW', text: '🇿🇼 짐바브웨 (Zimbabwe)' }
		    ];